### PR TITLE
fix(colors): add map with grades to scss output, add black100, white0, yellow20, and orange40 vars

### LINKED ISSUE #136: Export scss color map for colors
## Context 

In the old internal color package we are using, we have a useful scss color map that is exported along with all of the color variables, structured like this:

```
$ibm-color-map: (
  'blue': (
    10: $ibm-color__blue-10,
    20: $ibm-color__blue-20,
    30: $ibm-color__blue-30,
    40: $ibm-color__blue-40,
    50: $ibm-color__blue-50,
    60: $ibm-color__blue-60,
    70: $ibm-color__blue-70,
    80: $ibm-color__blue-80,
    90: $ibm-color__blue-90,
    100: $ibm-color__blue-100,
  ),
'cool-gray': (
    10: $ibm-color__cool-gray-10,
    20: $ibm-color__cool-gray-20,
    30: $ibm-color__cool-gray-30,
    40: $ibm-color__cool-gray-40,
    50: $ibm-color__cool-gray-50,
    60: $ibm-color__cool-gray-60,
    70: $ibm-color__cool-gray-70,
    80: $ibm-color__cool-gray-80,
    90: $ibm-color__cool-gray-90,
    100: $ibm-color__cool-gray-100,
  ),

 ...

);
```

It's very useful for us because we mix some colors in a few scss function and use steps, etc. So the map allows us to quick access a color by step and then manipulate it.

### Request

Can you all add a color map with your exported scss, structured similarly to the example above, so we can use it in our existing scss functions? 🙏 😅

### PR DESCRIPTION
**Pull request by jendowns**
Closes #136 

Per my issue description in #136, the color package we were previously using offered a color map with grades, allowing us to easily blend colors with mixins.

#### Changelog

**New**

- Per my comment here https://github.com/IBM/carbon-elements/issues/136#issuecomment-446000744, I wasn't sure what to do about `$ibm-colors__black` and `$ibm-colors__white` not having grades like the old color package did. So I added `$ibm-colors__black--100` and `$ibm-colors__white--0`. This helps keep continuity between this new `$ibm-color-map` and the old one, and it ensures that all colors now have a variable with a grade.

**Changed**

- add `$ibm-color-map` to scss output, which includes color entries organized by colors and then grade of color.

### CODE REVIEW

File: packages/colors/src/build.js [hunk 1]
```diff
@@ -47,13 +51,39 @@ async function build() {
     const variable = `$${PREFIX}-colors__${name}--${grade}`;
     colorsByValue[value] = variable;
 
+    // Collect color names and formatted scss color variables with grades.
+    colorsArray.push({
+      name,
+      grade: `${grade}: ${variable}`,
```
Comment (jendowns) [inline packages/colors/src/build.js]: Not sure if this is clear enough, but this line `${grade}: ${variable}` comes out to be something like `10: $ibm-colors__red--10` &  it's mean to be the final format of each color grade entry in the color map, like this:
screen shot 2018-12-11 at 11 53 53 am

**Comment by joshblack** [comment]
Thanks for doing this @jendowns! I think the only question I have about this is switching `black` to `black100` and `white` to `white0`. Neither black or white have a swatch and so it'd be nice if we could only surface the `0` or `100` distinction in the map that you were referring to. What do you think?

**Comment by jendowns** [comment]
@joshblack That's fair... what if I did this just outside of `colorsSource`, before I start creating color entries for the new map?

```javascript
colorsArray.push(
    { name: 'black', grade: `100: $${PREFIX}-colors__black--100` },
    { name: 'white', grade: `0: $${PREFIX}-colors__white--0` },
  );

uniqueColors.push('black', 'white');
```

It still builds the same map, but new variables are no longer required.
